version: '3.7'
services:
  backend:
    build:
      context: backend
      dockerfile: docker/Dockerfile
      target: dev
    env_file:
      - ./backend/.env.example
    environment:
      ENVIRONMENT: test
      JSON_API_PAGINATION_LINKS_ENABLED: 1
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: posts-app
      POSTGRES_PASSWORD: posts-app
      ALLOW_IP_RANGE: 0.0.0.0/0
    command: -c log_min_messages=PANIC -c log_min_error_statement=PANIC
