# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.3"

gem "active_model_serializers", "~> 0.10.0"
gem "activerecord", "~> 6.1.3"
gem "activesupport", "~> 6.1.3"
gem "dry-struct", "~> 1.4"
gem "json", "~> 2.5.1"
gem "paranoia", "~> 2.2"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "rack", "~> 2.2.3"

group :development, :test, :swagger do
  gem "brakeman"
  gem "bullet"
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "dotenv"
  gem "factory_bot_rails", ">= 5.0.1"
  gem "faker"
  gem "rspec-rails", "~> 4.0.1"
  gem "rswag"
  gem "simplecov", ">= 0.16.1"
end

group :test, :swagger do
  gem "database_cleaner"
  gem "shoulda-matchers", "~> 3.1", ">= 3.1.3"
end

group :swagger do
  gem "activerecord-nulldb-adapter"
end
