# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.3"

gem "active_model_serializers", "~> 0.10.0"
gem "activerecord", "~> 6.1.3"
gem "activesupport", "~> 6.1.3"
gem "dry-struct", "~> 1.4"
gem "json", "~> 2.5.1"
gem "json-schema"
gem "paranoia", "~> 2.2"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "rack", "~> 2.2.3"

group :development, :test do
  gem "bullet"
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "database_cleaner"
  gem "dotenv"
  gem "factory_bot", ">= 6.2.0"
  gem "faker"
  gem "rexml"
  gem "rspec-core", "~> 3.10.1"
  gem "rspec-expectations", "~> 3.10.1"
  gem "rspec-mocks", "~> 3.10.1"
  gem "rspec-support", "~> 3.10.1"
  gem "rubocop", require: false
  gem "rubocop-rspec", require: false
  gem "rubycritic"
  gem "shoulda-matchers", "~> 3.1", ">= 3.1.3"
  gem "simplecov", ">= 0.16.1"
end
